services:
  - type: web
    name: basse-online-shop
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    plan: free
    envVars:
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: WAYCHIT_API_KEY
        sync: false
      - key: WAYCHIT_WEBHOOK_SECRET
        sync: false
      - key: WAYCHIT_STATIC_URL
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
      - key: BASSE_MARKET_WHATSAPP
        value: 2206963349
      - key: DATA_DIR
        value: /opt/render/project/src/server/data
