let token=localStorage.getItem("basseAdminToken")||"";const H=()=>({Authorization:"Bearer "+token}),$=id=>document.getElementById(id),money=n=>"D"+Number(n||0).toLocaleString();
async function login(){let r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("email").value,password:$("password").value})}),d=await r.json();if(!r.ok)return alert(d.error||"Invalid login");token=d.token;localStorage.setItem("basseAdminToken",token);start()}
function start(){$("login").classList.add("hidden");$("app").classList.remove("hidden");refresh();setInterval(refresh,15000)}
function logout(){localStorage.removeItem("basseAdminToken");location.reload()}
function show(id,btn){["dashboard","products","orders"].forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden");$("title").textContent=id[0].toUpperCase()+id.slice(1);document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));if(btn)btn.classList.add("active");refresh()}
async function refresh(){let [s,p,o]=await Promise.all([fetch("/api/admin/stats",{headers:H()}),fetch("/api/admin/products",{headers:H()}),fetch("/api/admin/orders",{headers:H()})]);if(s.status===401){logout();return}let st=await s.json(),ps=await p.json(),os=await o.json();$("productsCount").textContent=st.products;$("ordersCount").textContent=st.orders;$("pendingCount").textContent=st.pending;$("paidCount").textContent=st.paid;$("sales").textContent=money(st.sales);$("recent").innerHTML=os.slice(0,7).map(o=>`<div class="order"><b>${esc(o.id)}</b> · ${esc(o.product_name)} × ${o.quantity}<br>${esc(o.customer_name)} · ${money(o.total)} · <span class="${o.payment_status==="PAID"?"paid":"pending"}">${o.payment_status}</span></div>`).join("")||"<p>No orders yet.</p>";$("productTable").innerHTML=`<div class="tablewrap"><table class="table"><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr>${ps.map(p=>`<tr><td><img class="thumb" src="${p.image||""}"><br><b>${esc(p.name)}</b></td><td>${esc(p.category)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><span class="badge paid">LIVE</span></td><td><button onclick='editProduct(${JSON.stringify(p)})'>Edit</button><button class="danger" onclick="deleteProduct(${p.id})">Delete</button></td></tr>`).join("")}</table></div>`;$("orderTable").innerHTML=os.map(o=>`<div class="order"><b>${esc(o.id)}</b> · ${esc(o.customer_name)} · ${esc(o.product_name)} × ${o.quantity} · <b>${money(o.total)}</b> · <span class="${o.payment_status==="PAID"?"paid":"pending"}">${o.payment_status}</span><br><small>WhatsApp +${esc(o.whatsapp)} · ${esc(o.location)} · ${esc(o.order_status)}</small> ${o.payment_status!=="PAID"?`<button onclick="confirmPay('${o.id}')">✓ CONFIRM PAYMENT</button>`:""} </div>`).join("")||"<p>No orders yet.</p>"}
function openProduct(p=null){$("editor").innerHTML=`<h2>${p?"Edit":"Add"} Product</h2><form id="productForm" class="form"><label>Product picture</label><input name="image" type="file" accept="image/*"><label>Image URL (optional)</label><input name="imageUrl" value="${esc(p?.image||"")}"><label>Product name</label><input name="name" value="${esc(p?.name||"")}" required><label>Category</label><select name="category">${["Fashion","Electronics","Phones","Beauty","Home & Living","Accessories"].map(c=>`<option ${c===p?.category?"selected":""}>${c}</option>`).join("")}</select><label>Price (Dalasi)</label><input name="price" type="number" value="${p?.price||""}" required><label>Stock</label><input name="stock" type="number" value="${p?.stock??0}" required><label>Description</label><textarea name="description">${esc(p?.description||"")}</textarea><button type="submit">${p?"SAVE CHANGES":"PUBLISH PRODUCT"}</button></form>`;$("modal").classList.remove("hidden");$("productForm").onsubmit=e=>saveProduct(e,p?.id)}
function editProduct(p){openProduct(p)}async function saveProduct(e,id){e.preventDefault();let r=await fetch(id?"/api/admin/products/"+id:"/api/admin/products",{method:id?"PUT":"POST",headers:H(),body:new FormData(e.target)}),d=await r.json();if(!r.ok)return alert(d.error||"Save failed");closeModal();alert(id?"Product updated — marketplace updated automatically.":"Product published — it is now live on the marketplace.");refresh()}
async function deleteProduct(id){if(!confirm("Delete this product from the customer marketplace?"))return;let r=await fetch("/api/admin/products/"+id,{method:"DELETE",headers:H()});if(r.ok)refresh()}
async function confirmPay(id){let r=await fetch("/api/admin/orders/"+id+"/payment",{method:"POST",headers:H()});if(r.ok){alert("Payment confirmed. Order is now PROCESSING.");refresh()}}
function closeModal(){$("modal").classList.add("hidden")}function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}if(token)start();