const express=require("express"),Database=require("better-sqlite3"),multer=require("multer"),path=require("path"),crypto=require("crypto"),fs=require("fs");
const app=express(),PORT=process.env.PORT||3000,ROOT=__dirname,DATA_DIR=process.env.DATA_DIR||path.join(ROOT,"data");fs.mkdirSync(DATA_DIR,{recursive:true});fs.mkdirSync(path.join(DATA_DIR,"uploads"),{recursive:true});
app.use(express.json({limit:"2mb",verify:(req,res,buf)=>{if(req.originalUrl==="/api/waychit/webhook")req.rawBody=buf.toString("utf8")}}));
app.use("/uploads",express.static(path.join(DATA_DIR,"uploads")));
app.use("/admin",express.static(path.join(ROOT,"../admin")));
app.use("/",express.static(path.join(ROOT,"../marketplace")));
const db=new Database(path.join(DATA_DIR,"basse-shop.db"));db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,category TEXT,price INTEGER,stock INTEGER,description TEXT,image TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,product_id INTEGER,product_name TEXT,quantity INTEGER,customer_name TEXT,whatsapp TEXT,location TEXT,total INTEGER,payment_status TEXT DEFAULT 'PENDING',order_status TEXT DEFAULT 'NEW',waychit_request_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
if(!db.prepare("SELECT COUNT(*) c FROM products").get().c){let q=db.prepare("INSERT INTO products(name,category,price,stock,description,image) VALUES(?,?,?,?,?,?)");[
["Premium Blue Hoodie","Fashion",850,15,"Comfortable everyday hoodie.","https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=80"],
["Wireless Headphones","Electronics",1500,10,"Clear wireless sound.","https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80"],
["Smartphone 128GB","Phones",3290,8,"Modern 128GB smartphone.","https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80"],
["Beauty Care Set","Beauty",450,20,"Everyday beauty care bundle.","https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80"],
["Leather Handbag","Accessories",1200,12,"Elegant everyday handbag.","https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80"],
["Smart Watch Pro","Electronics",2200,9,"Smart everyday watch.","https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80"]].forEach(x=>q.run(...x))}
const upload=multer({storage:multer.diskStorage({destination:path.join(DATA_DIR,"uploads"),filename:(r,f,cb)=>cb(null,crypto.randomBytes(8).toString("hex")+path.extname(f.originalname))}),limits:{fileSize:6e6}});
const sessions=new Map();function guard(req,res,next){if(!sessions.has((req.headers.authorization||"").replace("Bearer ","")))return res.status(401).json({error:"Admin login required"});next()}
app.get("/api/products",(req,res)=>{let p=db.prepare("SELECT * FROM products WHERE active=1 ORDER BY id DESC").all(),c=req.query.category||"All",q=(req.query.q||"").toLowerCase();if(c!=="All")p=p.filter(x=>x.category===c);if(q)p=p.filter(x=>(x.name+" "+x.category+" "+x.description).toLowerCase().includes(q));res.json(p)});
app.get("/api/products/:id",(req,res)=>{let p=db.prepare("SELECT * FROM products WHERE id=? AND active=1").get(req.params.id);p?res.json(p):res.status(404).json({error:"Product not found"})});
app.post("/api/admin/login",(req,res)=>{if(req.body.email===process.env.ADMIN_EMAIL&&req.body.password===process.env.ADMIN_PASSWORD){let t=crypto.randomBytes(32).toString("hex");sessions.set(t,Date.now()+432e5);res.json({token:t})}else res.status(401).json({error:"Invalid admin login"})});
app.get("/api/admin/products",guard,(req,res)=>res.json(db.prepare("SELECT * FROM products ORDER BY id DESC").all()));
app.post("/api/admin/products",guard,upload.single("image"),(req,res)=>{let b=req.body,img=req.file?"/uploads/"+req.file.filename:b.imageUrl||"";let x=db.prepare("INSERT INTO products(name,category,price,stock,description,image) VALUES(?,?,?,?,?,?)").run(b.name,b.category,+b.price,+b.stock||0,b.description||"",img);res.json(db.prepare("SELECT * FROM products WHERE id=?").get(x.lastInsertRowid))});
app.put("/api/admin/products/:id",guard,upload.single("image"),(req,res)=>{let p=db.prepare("SELECT * FROM products WHERE id=?").get(req.params.id);if(!p)return res.status(404).json({error:"Product not found"});let b=req.body,img=req.file?"/uploads/"+req.file.filename:(b.imageUrl||p.image);db.prepare("UPDATE products SET name=?,category=?,price=?,stock=?,description=?,image=? WHERE id=?").run(b.name,b.category,+b.price,+b.stock,b.description||"",img,p.id);res.json(db.prepare("SELECT * FROM products WHERE id=?").get(p.id))});
app.delete("/api/admin/products/:id",guard,(req,res)=>{db.prepare("UPDATE products SET active=0 WHERE id=?").run(req.params.id);res.json({ok:true})});
app.get("/api/admin/orders",guard,(req,res)=>res.json(db.prepare("SELECT * FROM orders ORDER BY datetime(created_at) DESC").all()));
app.get("/api/admin/stats",guard,(req,res)=>res.json({products:db.prepare("SELECT COUNT(*) c FROM products WHERE active=1").get().c,orders:db.prepare("SELECT COUNT(*) c FROM orders").get().c,pending:db.prepare("SELECT COUNT(*) c FROM orders WHERE payment_status='PENDING'").get().c,paid:db.prepare("SELECT COUNT(*) c FROM orders WHERE payment_status='PAID'").get().c,cancelled:db.prepare("SELECT COUNT(*) c FROM orders WHERE payment_status='CANCELLED' OR order_status='CANCELLED'").get().c,refunded:db.prepare("SELECT COUNT(*) c FROM orders WHERE payment_status='REFUNDED'").get().c,sales:db.prepare("SELECT COALESCE(SUM(total),0) s FROM orders WHERE payment_status='PAID' AND order_status!='CANCELLED' AND date(created_at)=date('now','localtime')").get().s}));
app.post("/api/orders",async(req,res)=>{let p=db.prepare("SELECT * FROM products WHERE id=? AND active=1").get(req.body.productId),q=Math.max(1,+req.body.quantity||1);if(!p)return res.status(404).json({error:"Product unavailable"});if(q>p.stock)return res.status(400).json({error:"Not enough stock"});let id="BOS-"+crypto.randomBytes(4).toString("hex").toUpperCase(),phone="220"+String(req.body.whatsapp).replace(/\D/g,"").replace(/^220/,""),total=p.price*q;db.prepare("INSERT INTO orders(id,product_id,product_name,quantity,customer_name,whatsapp,location,total) VALUES(?,?,?,?,?,?,?,?)").run(id,p.id,p.name,q,req.body.name,phone,req.body.location,total);let paymentUrl="";if(process.env.WAYCHIT_API_KEY&&process.env.PUBLIC_BASE_URL){try{let r=await fetch("https://api.waychit.com/v1/payment-requests",{method:"POST",headers:{"Authorization":"Bearer "+process.env.WAYCHIT_API_KEY,"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({amount:total,description:p.name+" x "+q,clientReference:id,successRedirectUrl:process.env.PUBLIC_BASE_URL+"/?payment=success&order="+id,failureRedirectUrl:process.env.PUBLIC_BASE_URL+"/?payment=failed&order="+id})}),d=await r.json();if(r.ok&&d.paymentRequest){paymentUrl=d.paymentRequest.waychitLaunchUrl;db.prepare("UPDATE orders SET waychit_request_id=? WHERE id=?").run(d.paymentRequest.id,id)}}catch(e){console.error(e.message)}}res.status(201).json({order:db.prepare("SELECT * FROM orders WHERE id=?").get(id),paymentUrl,whatsappSupport:String(process.env.WHATSAPP_SUPPORT||"").replace(/\D/g,"")})});
app.get("/api/order/:id",(req,res)=>{let o=db.prepare("SELECT * FROM orders WHERE id=?").get(req.params.id);o?res.json({...o,whatsappSupport:String(process.env.WHATSAPP_SUPPORT||"").replace(/\D/g,"")}):res.status(404).json({error:"Order not found"})});
app.post("/api/admin/orders/:id/payment",guard,(req,res)=>{let o=db.prepare("SELECT * FROM orders WHERE id=?").get(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});if(o.payment_status==='REFUNDED'||o.payment_status==='CANCELLED')return res.status(400).json({error:'This payment is already closed.'});db.prepare("UPDATE orders SET payment_status='PAID',order_status='PROCESSING' WHERE id=?").run(req.params.id);res.json({ok:true})});
app.post("/api/admin/orders/:id/cancel-payment",guard,(req,res)=>{let o=db.prepare("SELECT * FROM orders WHERE id=?").get(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});if(o.payment_status==='PAID')return res.status(400).json({error:'A paid order cannot be cancelled. Use Refund instead.'});db.prepare("UPDATE orders SET payment_status='CANCELLED',order_status='CANCELLED' WHERE id=?").run(req.params.id);res.json({ok:true})});
app.post("/api/admin/orders/:id/refund",guard,(req,res)=>{let o=db.prepare("SELECT * FROM orders WHERE id=?").get(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});if(o.payment_status!=='PAID')return res.status(400).json({error:'Only paid orders can be marked refunded.'});db.prepare("UPDATE orders SET payment_status='REFUNDED',order_status='REFUNDED' WHERE id=?").run(req.params.id);res.json({ok:true,notice:'Order marked refunded. Complete the actual money reversal in Waychit if required.'})});
app.post("/api/admin/orders/:id/reopen",guard,(req,res)=>{let o=db.prepare("SELECT * FROM orders WHERE id=?").get(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});db.prepare("UPDATE orders SET payment_status='PENDING',order_status='NEW' WHERE id=?").run(req.params.id);res.json({ok:true})});
app.patch("/api/admin/orders/:id/status",guard,(req,res)=>{let allowed=['NEW','PROCESSING','READY','DELIVERED','CANCELLED','REFUNDED'];let status=String(req.body.status||'').toUpperCase();if(!allowed.includes(status))return res.status(400).json({error:'Invalid order status'});db.prepare("UPDATE orders SET order_status=? WHERE id=?").run(status,req.params.id);res.json({ok:true})});
app.post("/api/waychit/webhook",(req,res)=>{let sig=req.headers["waychit-signature"],secret=process.env.WAYCHIT_WEBHOOK_SECRET,raw=req.rawBody||"";if(!sig||!secret||!raw)return res.status(400).send("Webhook not configured");try{let parts=String(sig).split(","),t=parts.find(x=>x.trim().startsWith("t="))?.trim().split("=")[1],sigs=parts.filter(x=>x.trim().startsWith("v1=")).map(x=>x.trim().split("=")[1]);if(!t||!sigs.length||Math.abs(Date.now()/1000-Number(t))>300)return res.status(400).send("Invalid signature");let expected=crypto.createHmac("sha256",secret).update(`${t}.${raw}`).digest("hex");if(!sigs.includes(expected))return res.status(400).send("Invalid signature");let e=JSON.parse(raw),ref=e.paymentRequest?.clientReference||e.paymentSession?.clientReference||e.data?.clientReference;if((e.type==="payment.request.completed"||e.type==="payment.session.completed")&&ref)db.prepare("UPDATE orders SET payment_status='PAID',order_status='PROCESSING' WHERE id=?").run(ref);res.sendStatus(200)}catch(e){res.status(400).send("Bad webhook")}});
app.listen(PORT,"0.0.0.0",()=>console.log("BASSE ONLINE SHOP running on "+PORT));