let category="All",cart=JSON.parse(localStorage.getItem("basseCart")||"[]"),selected=null;
const $=id=>document.getElementById(id),money=n=>"D"+Number(n||0).toLocaleString();
async function loadProducts(){let r=await fetch("/api/products?category="+encodeURIComponent(category)+"&q="+encodeURIComponent($("search").value));let ps=await r.json();$("count").textContent=ps.length+" products";$("grid").innerHTML=ps.map(p=>`<article class="product"><div class="pic"><img src="${p.image||""}" alt="${esc(p.name)}" loading="lazy"><span class="tag">${esc(p.category)}</span></div><div class="info"><h3>${esc(p.name)}</h3><p>${esc(p.description||"Quality product from BASSE ONLINE SHOP.")}</p><div class="price">${money(p.price)}</div><button class="buy" onclick="buy(${p.id})">BUY NOW</button></div></article>`).join("")}
function setCat(c,b){category=c;document.querySelectorAll(".cats button").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadProducts()}
async function buy(id){selected=await(await fetch("/api/products/"+id)).json();$("modal").innerHTML=`<div class="sheet"><button class="close" onclick="closeModal()">×</button><h2>Buy ${esc(selected.name)}</h2><p>${esc(selected.description||"")}</p><div class="form"><label>Quantity</label><input id="qty" type="number" min="1" max="${selected.stock}" value="1"><label>Full Name</label><input id="name" placeholder="Your name"><label>WhatsApp Number</label><input id="phone" inputmode="numeric" placeholder="7XXXXXX"><small>+220 will be added automatically.</small><label>Location</label><select id="loc"><option>Basse</option><option>Bansang</option><option>Fatoto</option><option>Other</option></select><div class="summary"><div class="row"><span>Product</span><b>${money(selected.price)}</b></div><div class="row"><span>Total</span><b id="total">${money(selected.price)}</b></div></div><button class="pay" onclick="placeOrder()">💳 PAY WITH WAYCHIT</button></div></div>`;$("modal").classList.add("show");$("qty").oninput=()=>$("total").textContent=money(selected.price*Math.max(1,+$("qty").value||1))}
async function placeOrder(){let q=Math.max(1,+$("qty").value||1),phone=$("phone").value.replace(/\D/g,"").replace(/^220/,"");if(!$("name").value.trim()||phone.length<6)return toast("Enter your name and WhatsApp number.");let r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:selected.id,quantity:q,name:$("name").value.trim(),whatsapp:phone,location:$("loc").value})}),d=await r.json();if(!r.ok)return toast(d.error||"Order failed");let msg=`Hello BASSE ONLINE SHOP 👋%0A%0AI have completed payment for my order.%0A%0AOrder: ${d.order.id}%0AProduct: ${d.order.product_name} × ${d.order.quantity}%0ATotal: ${money(d.order.total)}%0ALocation: ${d.order.location}%0A%0APlease confirm my payment. Thank you.`;localStorage.setItem("basseLastOrder",JSON.stringify(d.order));if(d.paymentUrl){location.href=d.paymentUrl}else{showReturn(d.order,msg,false)}}
function showReturn(o,msg,paid){$("modal").innerHTML=`<div class="sheet" style="text-align:center"><button class="close" onclick="closeModal()">×</button><div style="font-size:52px">${paid?"🎉":"🧾"}</div><h2>${paid?"Thank you for shopping with us!":"Order received"}</h2><p>${paid?"Your payment was completed successfully.":"Your order has been received."}</p><div class="summary"><div class="row"><span>Order</span><b>${o.id}</b></div><div class="row"><span>Total</span><b>${money(o.total)}</b></div><div class="row"><span>Payment</span><b>${paid?"PAID":"PENDING"}</b></div></div><a class="whats" href="https://wa.me/${o.whatsapp}?text=${msg}">💬 SEND ORDER ON WHATSAPP</a></div>`;$("modal").classList.add("show")}
function handleReturn(){let u=new URLSearchParams(location.search),st=u.get("payment"),id=u.get("order");if(!id||!st)return;fetch("/api/order/"+id).then(r=>r.json()).then(o=>{let msg=`Hello BASSE ONLINE SHOP 👋%0AI have completed payment for order ${o.id}.%0ATotal: ${money(o.total)}.`;showReturn(o,msg,st==="success");history.replaceState({},document.title,"/")})}
function closeModal(){$("modal").classList.remove("show")};function openCart(){toast("Cart is ready — checkout uses the same secure order system.")};function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2500)}function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
loadProducts();handleReturn();