let token=localStorage.getItem("basseDriverToken")||"";const $=x=>document.getElementById(x);const H=()=>token?{Authorization:"Bearer "+token}:{};let watchIds={};let activeGps=null;
async function api(u,o={}){const r=await fetch(u,{...o,headers:{...H(),...(o.headers||{})},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
async function login(){const phone=$("phone").value.trim(),pin=$("pin").value.trim();try{const d=await api("/api/driver/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({whatsapp:phone,pin})});token=d.token;localStorage.setItem("basseDriverToken",token);start()}catch(e){alert(e.message)}}
function start(){$("login").classList.add("hidden");$("app").classList.remove("hidden");load();setInterval(load,8000)}
async function load(){try{const me=await api("/api/driver/me");$("driverName").textContent=me.full_name;const ds=await api("/api/driver/deliveries");$("list").innerHTML=ds.map(render).join("")||'<div class="card"><b>No deliveries assigned yet.</b><p class="muted">Admin will assign your deliveries here.</p></div>'}catch(e){if(/login|driver/i.test(e.message))logout()}}
function render(d){const live=d.status==="ON_THE_WAY"||d.status==="ARRIVED";return `<div class="order-card"><div class="order-head"><b>#${d.order_id}</b><span class="status">${d.status.replaceAll("_"," ")}</span></div><h3>${esc(d.product_name)} × ${d.quantity}</h3><p class="muted">Customer: ${esc(d.customer_name||"Customer")}<br>WhatsApp: +${esc(d.whatsapp||"")}<br>Location: ${esc(d.location||"")}</p><div class="actions">${d.status==="ASSIGNED"?`<button onclick="setStatus(${d.id},'PICKED_UP')">📦 PICKED UP</button>`:""}${d.status==="PICKED_UP"?`<button onclick="setStatus(${d.id},'ON_THE_WAY');startGps(${d.id})">🚚 START DELIVERY & GPS</button>`:""}${live?`<button onclick="startGps(${d.id})">📍 SHARE LIVE LOCATION</button><button onclick="setStatus(${d.id},'ARRIVED')">📍 ARRIVED</button>`:""}${d.status==="ARRIVED"?`<button onclick="setStatus(${d.id},'DELIVERED');stopGps(${d.id})">✅ MARK DELIVERED</button>`:""}</div></div>`}
async function setStatus(id,status){try{await api("/api/driver/deliveries/"+id+"/status",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(status==="ON_THE_WAY")startGps(id);if(status==="DELIVERED")stopGps(id);load()}catch(e){alert(e.message)}}
function startGps(id){if(!navigator.geolocation){alert("This phone does not support GPS.");return}stopGps(id);$("gpsState").textContent="Location sharing is ON";activeGps=navigator.geolocation.watchPosition(async p=>{try{await api("/api/driver/deliveries/"+id+"/location",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy})})}catch{}},e=>{$("gpsState").textContent="GPS permission/location unavailable";},{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
function stopGps(){if(activeGps!==null&&navigator.geolocation){navigator.geolocation.clearWatch(activeGps);activeGps=null}$("gpsState").textContent="Location sharing is OFF"}
function logout(){stopGps();localStorage.removeItem("basseDriverToken");token="";$("app").classList.add("hidden");$("login").classList.remove("hidden")}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
if(token)start();