let token=localStorage.getItem("basseDriverToken")||"";const $=x=>document.getElementById(x);const H=()=>token?{Authorization:"Bearer "+token}:{};let activeGps=null;let maps={};
const BASSE_MAP_STYLE="https://tiles.openfreemap.org/styles/liberty";let mapLibrePromise=null;
function ensureMapLibre(){if(window.maplibregl)return Promise.resolve(window.maplibregl);if(mapLibrePromise)return mapLibrePromise;mapLibrePromise=new Promise(resolve=>{if(!document.querySelector('link[data-basse-maplibre]')){const css=document.createElement("link");css.rel="stylesheet";css.href="https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.css";css.dataset.basseMaplibre="1";document.head.appendChild(css)}const sc=document.createElement("script");sc.src="https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.js";sc.onload=()=>resolve(window.maplibregl);sc.onerror=()=>resolve(null);document.head.appendChild(sc)});return mapLibrePromise}
function mapMarker(label,type){const el=document.createElement("div");el.className=`basse-map-marker ${type}-marker maplibre-marker`;el.innerHTML=`<span></span><b>${label}</b>`;return el}
let deliveries=[];let lastStructure="";let lastGpsSentAt=0;let lastGpsSent={lat:null,lng:null};
async function api(u,o={}){const r=await fetch(u,{...o,headers:{...H(),...(o.headers||{})},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
async function login(){const phone=$("phone").value.trim(),pin=$("pin").value.trim(),btn=$("loginBtn"),err=$("loginError");if(err){err.style.display="none";err.textContent=""}if(btn){btn.disabled=true;btn.textContent="LOGGING IN…"}try{const d=await api("/api/driver/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({whatsapp:phone,pin})});token=d.token;localStorage.setItem("basseDriverToken",token);start()}catch(e){if(err){err.textContent=e.message||"Login failed";err.style.display="block"}else alert(e.message)}finally{if(btn){btn.disabled=false;btn.textContent="LOGIN"}}}
function start(){$("login").classList.add("hidden");$("app").classList.remove("hidden");ensureMapLibre().then(()=>load());if(window.__driverTimer)clearInterval(window.__driverTimer);window.__driverTimer=setInterval(load,12000)}
function structureSignature(ds){return ds.map(d=>[d.id,d.order_id,d.status,d.customer_lat,d.customer_lng,d.customer_name,d.location,d.product_name,d.quantity].join("|")).join(";;")}
async function load(){try{const me=await api("/api/driver/me");$("driverName").textContent=me.full_name;const ds=await api("/api/driver/deliveries");deliveries=ds;const sig=structureSignature(ds);if(sig!==lastStructure){Object.keys(maps).forEach(k=>{try{maps[k].map.remove()}catch{}delete maps[k]});$("list").innerHTML=ds.map(render).join("")||'<div class="card"><b>No deliveries assigned yet.</b><p class="muted">Admin will assign your deliveries here.</p></div>';lastStructure=sig;requestAnimationFrame(()=>setTimeout(ensureDriverMaps,80));setTimeout(ensureDriverMaps,350)}
const ids=new Set(ds.map(d=>String(d.id)));Object.keys(maps).forEach(k=>{if(!ids.has(String(k))){try{maps[k].map.remove()}catch{}delete maps[k]}});ds.forEach(d=>{if(Number.isFinite(Number(d.customer_lat))&&Number.isFinite(Number(d.customer_lng))){if(window.maplibregl){if(maps[d.id])syncMapData(d);else initMap(d)}}});
}catch(e){if(/login|driver/i.test(e.message))logout()}}
function render(d){const live=d.status==="ON_THE_WAY"||d.status==="ARRIVED";const hasCustomer=Number.isFinite(Number(d.customer_lat))&&Number.isFinite(Number(d.customer_lng));return `<div class="order-card"><div class="order-head"><b>#${esc(d.order_id)}</b><span class="status">${d.status.replaceAll("_"," ")}</span></div><h3>${esc(d.product_name)} × ${d.quantity}</h3><p class="muted">Customer: ${esc(d.customer_name||"Customer")}<br>WhatsApp: +${esc(d.whatsapp||"")}<br>Location: ${esc(d.location||"")}</p><div class="driver-map-head"><b> Delivery Map</b><small>${hasCustomer?(d.lat&&d.lng?"Live driver position":"Customer location saved"):"Customer GPS location not captured"}</small></div><div id="map-${d.id}" class="driver-map">${hasCustomer?"":"<div class=\"map-empty\"> Customer GPS was not captured for this order.<br><small>The written delivery location is shown above.</small></div>"}</div><div class="map-legend"><span> Customer</span><span> Driver</span><span>━━ Live distance line</span></div><div class="actions">${d.status==="ASSIGNED"?`<button onclick="setStatus(${d.id},'ACCEPTED')"> ACCEPT DELIVERY</button>`:""}${d.status==="ACCEPTED"?`<button onclick="setStatus(${d.id},'PICKED_UP')"> PICKED UP</button>`:""}${d.status==="PICKED_UP"?`<button onclick="setStatus(${d.id},'ON_THE_WAY')"> START DELIVERY & GPS</button>`:""}${live?`<button class="secondary" onclick="startGps(${d.id})"> SHARE LIVE LOCATION</button><button class="secondary" onclick="setStatus(${d.id},'ARRIVED')"> ARRIVED</button>`:""}${d.status==="ARRIVED"?`<button onclick="setStatus(${d.id},'DELIVERED');stopGps()"> MARK DELIVERED</button>`:""}</div></div>`}
function initMap(d){
  const el=$("map-"+d.id);if(!el||!Number.isFinite(Number(d.customer_lat))||!Number.isFinite(Number(d.customer_lng)))return;
  if(!window.maplibregl){el.innerHTML='<div class="map-empty">Map service is loading…</div>';return}
  try{if(maps[d.id]){try{maps[d.id].map.remove()}catch{}delete maps[d.id]}const clat=Number(d.customer_lat),clng=Number(d.customer_lng);el.innerHTML="";const map=new maplibregl.Map({container:el,style:BASSE_MAP_STYLE,center:[clng,clat],zoom:15,attributionControl:true,dragRotate:false,touchPitchRotate:false});const customer=new maplibregl.Marker({element:mapMarker("Customer","customer")}).setLngLat([clng,clat]).addTo(map);maps[d.id]={map,customer,driver:null,clat,clng,initialFit:true};map.on("load",()=>syncMapData(d));requestAnimationFrame(()=>{try{map.resize()}catch{}})}catch(e){console.warn("Driver MapLibre map init failed",e)}}
function syncMapData(d){const m=maps[d.id];if(!m||!m.map.isStyleLoaded())return;const lat=Number(d.lat),lng=Number(d.lng);if(Number.isFinite(lat)&&Number.isFinite(lng)){if(!m.driver)m.driver=new maplibregl.Marker({element:mapMarker("Driver","driver")}).setLngLat([lng,lat]).addTo(m.map);else m.driver.setLngLat([lng,lat]);const coords=[[lng,lat],[m.clng,m.clat]];const src=m.map.getSource("basse-line");if(!src)m.map.addSource("basse-line",{type:"geojson",data:{type:"Feature",geometry:{type:"LineString",coordinates:coords}}});else src.setData({type:"Feature",geometry:{type:"LineString",coordinates:coords}});if(!m.map.getLayer("basse-line"))m.map.addLayer({id:"basse-line",type:"line",source:"basse-line",paint:{"line-color":"#2878ff","line-width":4,"line-dasharray":[2,2]}});if(m.initialFit){const b=new maplibregl.LngLatBounds([lng,lat],[lng,lat]);b.extend([m.clng,m.clat]);m.map.fitBounds(b,{padding:25,maxZoom:16});m.initialFit=false}}}
function updateDriverMap(id,lat,lng){const m=maps[id];if(!m||!m.map.isStyleLoaded())return;syncMapData({id,lat,lng,customer_lat:m.clat,customer_lng:m.clng})}
async function setStatus(id,status){try{await api("/api/driver/deliveries/"+id+"/status",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(status==="DELIVERED")stopGps();lastStructure="";await load();requestAnimationFrame(()=>setTimeout(ensureDriverMaps,100));if(status==="ON_THE_WAY")setTimeout(()=>{ensureDriverMaps();startGps(id)},180)}catch(e){alert(e.message)}}
function startGps(id){if(!navigator.geolocation){alert("This phone does not support GPS.");return}stopGps();lastGpsSentAt=0;lastGpsSent={lat:null,lng:null};$("gpsState").textContent="Getting fresh GPS location…";activeGps=navigator.geolocation.watchPosition(async p=>{const lat=p.coords.latitude,lng=p.coords.longitude,accuracy=Number(p.coords.accuracy||0);const inGambia=lat>=12.90&&lat<=13.90&&lng>=-17.20&&lng<=-13.40;if(!inGambia){$("gpsState").textContent="GPS looks incorrect/outside The Gambia • enable Precise Location";return}if(accuracy>1500){$("gpsState").textContent=`GPS accuracy is weak (±${Math.round(accuracy)}m) • waiting for a better reading…`;return}updateDriverMap(id,lat,lng);const now=Date.now();const moved=lastGpsSent.lat===null||Math.abs(lat-lastGpsSent.lat)>0.00002||Math.abs(lng-lastGpsSent.lng)>0.00002;if(now-lastGpsSentAt<3000&&!moved)return;lastGpsSentAt=now;lastGpsSent={lat,lng};try{await api("/api/driver/deliveries/"+id+"/location",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lat,lng,accuracy})});$("gpsState").textContent=`Location sharing is ON • GPS ±${Math.round(accuracy||0)}m`;}catch(e){$("gpsState").textContent=e.message||"GPS update failed"}},e=>{$("gpsState").textContent="GPS permission/location unavailable • enable Precise Location";},{enableHighAccuracy:true,maximumAge:0,timeout:20000})}
function stopGps(){if(activeGps!==null&&navigator.geolocation){navigator.geolocation.clearWatch(activeGps);activeGps=null}$('gpsState').textContent="Location sharing is OFF"}
function logout(){stopGps();if(window.__driverTimer)clearInterval(window.__driverTimer);Object.values(maps).forEach(m=>{try{m.map.remove()}catch{}});maps={};localStorage.removeItem("basseDriverToken");token="";$("app").classList.add("hidden");$("login").classList.remove("hidden")}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
if(token)start();
function ensureDriverMaps(){
  if(!window.maplibregl)return;
  deliveries.forEach(d=>{if(!Number.isFinite(Number(d.customer_lat))||!Number.isFinite(Number(d.customer_lng)))return;if(window.maplibregl&&maps[d.id]){try{maps[d.id].map.resize()}catch{}}else if(window.maplibregl)initMap(d)});
}
window.addEventListener("pageshow",()=>setTimeout(ensureDriverMaps,150));
document.addEventListener("visibilitychange",()=>{if(!document.hidden)setTimeout(ensureDriverMaps,150)});
window.addEventListener("resize",()=>Object.values(maps).forEach(m=>{try{m.map.resize()}catch{}}));
window.addEventListener("orientationchange",()=>setTimeout(()=>Object.values(maps).forEach(m=>{try{m.map.resize()}catch{}}),300));
